services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    volumes:
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    ports:
      - "8080:8080"
    command: headscale serve
    networks:
      - baquara_network

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    restart: unless-stopped
    networks:
      - baquara_network
    # A UI será acessada via Caddy, então não precisamos expor porta aqui
    environment:
      - HTTP_PORT=9090

networks:
  baquara_network:
    external: true